header__change_seq:string
header__change_oper:string
header__change_mask:string
header__stream_position:string
header__operation:string
header__transaction_id:string
header__timestamp:string
ZASTAW:string
ZADOCO:decimal(38,10)
ZAUPMJ:long
ZAUPMT:decimal(38,10)
ZADCTO:string
ZAKCOO:string
ZACT01:string
ZACT02:string
ZAPRIOR:string
ZACLST:string
ZADESC:string
ZAISSUE:string
ZASERK:decimal(38,10)
ZASCALL:string
ZAVRU:string
ZACALLRN:string
ZATASKNO:decimal(38,10)
ZATIMEZONES:string
ZADSAVNAME:string
ZAREGION:string
ZALNGP:string
ZAPARCALL:decimal(38,10)
ZACALLQ:decimal(38,10)
ZAAN8:decimal(38,10)
ZAPH1:string
ZAANC:decimal(38,10)
ZAIDLN:decimal(38,10)
ZAAR1:string
ZACPH:string
ZAWHO1:string
ZAREM1:string
ZAFAR1:string
ZACFAX1:string
ZAAAR1:string
ZAPHN1:string
ZACTR:string
ZAAN8CT1:decimal(38,10)
ZAIDLNC1:decimal(38,10)
ZAAR2:string
ZACPHC1:string
ZAWHO2:string
ZACEML1:string
ZAFAR2:string
ZACFAX2:string
ZAAAR2:string
ZAPHN2:string
ZAAN8CT2:decimal(38,10)
ZAIDLNC2:decimal(38,10)
ZAAR3:string
ZACPHC2:string
ZAWHO3:string
ZACEML2:string
ZAFAR3:string
ZACFAX3:string
ZAAAR3:string
ZAPHN3:string
ZAAN8CT3:decimal(38,10)
ZAIDLNC3:decimal(38,10)
ZAAR4:string
ZACPHC3:string
ZAWHO4:string
ZACEML3:string
ZAFAR4:string
ZACFAX4:string
ZAAAR4:string
ZAPHN4:string
ZANUMB:decimal(38,10)
ZAPRODF:string
ZAPRODM:string
ZAPRODC:string
ZAITM:decimal(38,10)
ZAMMCU:string
ZALOTN:string
ZAENV:string
ZALANO:decimal(38,10)
ZADOCZ:decimal(38,10)
ZARCTO:string
ZARKCO:string
ZARLIN:decimal(38,10)
ZACOCH:string
ZAOORN:string
ZAOCTO:string
ZAOKCO:string
ZADOC:decimal(38,10)
ZADCT:string
ZAKCO:string
ZADOCM:decimal(38,10)
ZADCTM:string
ZAKCOP:string
ZAENTCK:string
ZAGWAUT:string
ZABILL:string
ZAMTHPR:string
ZAGLCCV:string
ZAGLCNC:string
ZACOST:string
ZALNTY:string
ZARSTM:decimal(38,10)
ZAHMCU:string
ZAOBJ:string
ZASUB:string
ZACSCL:string
ZAISNO:decimal(38,10)
ZAAG:decimal(38,10)
ZAACR:decimal(38,10)
ZAMODE:string
ZACRCD:string
ZACRDC:string
ZAHRSO:decimal(38,10)
ZAAMTO:decimal(38,10)
ZAFAP:decimal(38,10)
ZADTBIL:long
ZAASN3:string
ZACOVGR:string
ZAMCUZ:string
ZACO:string
ZAPBTM:decimal(38,10)
ZAEFTB:long
ZAPETM:decimal(38,10)
ZAEND:long
ZADX:long
ZAINRT:decimal(38,10)
ZAONSDT:long
ZAONSTM:decimal(38,10)
ZADRQJ:long
ZADRQT:decimal(38,10)
ZASESD:long
ZASEED:long
ZASEST:decimal(38,10)
ZASEET:decimal(38,10)
ZADEF:long
ZADL01:string
ZATELH:decimal(38,10)
ZAEDAYS:decimal(38,10)
ZAIDYS:decimal(38,10)
ZACOMD:decimal(38,10)
ZACDATE:long
ZACTIME:decimal(38,10)
ZAESC1:string
ZAESC2:string
ZAESDTE:long
ZAESTME:decimal(38,10)
ZAJC01:string
ZAJC02:string
ZAJC03:string
ZAJC04:string
ZAJC05:string
ZAJC06:string
ZAJC07:string
ZAJC08:string
ZAJC09:string
ZAJC10:string
ZAZE01:string
ZAZE02:string
ZAZE03:string
ZAZE04:string
ZAZE05:string
ZAZE06:string
ZAZE07:string
ZAZE08:string
ZAZE09:string
ZAZE10:string
ZAURAB:decimal(38,10)
ZAURCD:string
ZAURAT:decimal(38,10)
ZAURDT:long
ZAURRF:string
ZAEFFT:long
ZACRTU:string
ZAUSER:string
ZAPID:string
ZAJOBN:string
ZATYPS:string
ZACRRM:string
ZACRR:decimal(38,10)
ZAPEFJ:long
ZABLCN:decimal(38,10)
ZAUM:string
ZAAMTFD:decimal(38,10)
ZAAMTFF:decimal(38,10)
ZAPCOVR:decimal(38,10)
ZAGWAFL:string
ZAGWANC:string
ZASERP:string
ZAANOB:decimal(38,10)
ZAUSA5:decimal(38,10)
ZAVR01:string
ZAMINHR:decimal(38,10)
ZAMINAD:decimal(38,10)
ZAMINAF:decimal(38,10)
ZADSFT:string
ZADSPC:decimal(38,10)
ZAIDSC:decimal(38,10)
ZACIDS:decimal(38,10)
ZAITAM:decimal(38,10)
ZACITX:decimal(38,10)
ZAJTAX:decimal(38,10)
ZAJTXF:decimal(38,10)
ZAAMTCD:decimal(38,10)
ZAAMTCF:decimal(38,10)
ZAATXCD:decimal(38,10)
ZAATXCF:decimal(38,10)
ZAEFTJ:long
ZAPTC:string
ZARYIN:string
ZATAX1:string
ZATXA1:string
ZAPRAN8:decimal(38,10)
ZAPRCNCT:string
ZAPRCIDLN:decimal(38,10)
ZAEXR1:string